import { useEffect } from 'react'
import { QueryClient } from '@tanstack/react-query'
import { createRootRouteWithContext, Outlet } from '@tanstack/react-router'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { TanStackRouterDevtools } from '@tanstack/react-router-devtools'
import { Toaster } from '@/components/ui/sonner'
import { NavigationProgress } from '@/components/navigation-progress'
import GeneralError from '@/features/errors/general-error'
import NotFoundError from '@/features/errors/not-found-error'

export const Route = createRootRouteWithContext<{
  queryClient: QueryClient
}>()({
  component: () => {
    // Gracefully handle legacy paths like /_authenticated/orders by redirecting to /orders
    useEffect(() => {
      if (typeof window !== 'undefined') {
        const p = window.location.pathname
        if (p.startsWith('/_authenticated')) {
          // Redirect to simplified paths generated by TanStack Router
          const target = p.replace('/_authenticated', '') || '/orders'
          // Ensure it begins with '/'
          const finalPath = target.startsWith('/') ? target : `/${target}`
          if (finalPath !== p) {
            window.location.replace(finalPath)
          }
        }
      }
    }, [])
    return (
      <>
        <NavigationProgress />
        <Outlet />
        <Toaster duration={50000} />
        {import.meta.env.MODE === 'development' && (
          <>
            <ReactQueryDevtools buttonPosition='bottom-left' />
            <TanStackRouterDevtools position='bottom-right' />
          </>
        )}
      </>
    )
  },
  notFoundComponent: NotFoundError,
  errorComponent: GeneralError,
})
